// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdD8GmIGpb9y8sYgU3AAckFxBjLGjYJv8',
    appId: '1:106794205937:web:025bfba77c29b83b8b9f50',
    messagingSenderId: '106794205937',
    projectId: 'pushnotification-aae0d',
    authDomain: 'pushnotification-aae0d.firebaseapp.com',
    storageBucket: 'pushnotification-aae0d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOYqBDphYjPJhmHXXnNtFa4W3RcYU5uF0',
    appId: '1:106794205937:android:71bbcf316317a33b8b9f50',
    messagingSenderId: '106794205937',
    projectId: 'pushnotification-aae0d',
    storageBucket: 'pushnotification-aae0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdAQCUTe2c8Bnbih8TsYBIcZEIkCqWZ3w',
    appId: '1:106794205937:ios:f26112765ff754e88b9f50',
    messagingSenderId: '106794205937',
    projectId: 'pushnotification-aae0d',
    storageBucket: 'pushnotification-aae0d.appspot.com',
    iosBundleId: 'com.example.giftShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdAQCUTe2c8Bnbih8TsYBIcZEIkCqWZ3w',
    appId: '1:106794205937:ios:f26112765ff754e88b9f50',
    messagingSenderId: '106794205937',
    projectId: 'pushnotification-aae0d',
    storageBucket: 'pushnotification-aae0d.appspot.com',
    iosBundleId: 'com.example.giftShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdD8GmIGpb9y8sYgU3AAckFxBjLGjYJv8',
    appId: '1:106794205937:web:31aaffc71b6871888b9f50',
    messagingSenderId: '106794205937',
    projectId: 'pushnotification-aae0d',
    authDomain: 'pushnotification-aae0d.firebaseapp.com',
    storageBucket: 'pushnotification-aae0d.appspot.com',
  );
}
